from pathlib import Path

p=Path('client/public/KIMIchord_trees_fixed.html')
s=p.read_text()

s=s.replace("examHistoryVisible:false,examHistory:[]};", "examHistoryVisible:false,examHistory:[],examKeyboardHint:false,examSettingsCollapsed:false,examScoreSeries:[] ,progressionSearch:'',progressionFavorites:[]};")
s=s.replace("S.examQuestionLimit=clampExamQuestionLimit(savedExamSettings.questionLimit);", "S.examQuestionLimit=clampExamQuestionLimit(savedExamSettings.questionLimit);\nS.examKeyboardHint=Boolean(savedExamSettings.keyboardHint);\ntry{S.progressionFavorites=JSON.parse(localStorage.getItem('kimichord.progressionFavorites')||'[]');if(!Array.isArray(S.progressionFavorites))S.progressionFavorites=[];}catch(error){S.progressionFavorites=[];}")
s=s.replace("<div class=\"exam-card-title\">隨堂考試</div>", "<div class=\"exam-card-title\">隨堂考試</div>\n        <button class=\"sb-btn exam-settings-toggle\" id=\"examSettingsToggle\" type=\"button\" aria-expanded=\"true\">設定（可收合）</button>\n        <div id=\"examSettingsBody\">")
s=s.replace("<div class=\"exam-live-status\" id=\"examLiveStatus\" aria-live=\"polite\">尚未開始</div>\n      </div>", "<div class=\"exam-live-status\" id=\"examLiveStatus\" aria-live=\"polite\">尚未開始</div>\n        <label class=\"exam-hint-toggle\"><input type=\"checkbox\" id=\"examKeyboardHint\"> 鍵盤正確提示（藍色提示，預設關閉）</label>\n        </div>\n      </div>")
s=s.replace("<button class=\"sb-btn\" id=\"commonProgressionApplyBtn\" type=\"button\">載入並播放常見進行</button>", "<button class=\"sb-btn\" id=\"commonProgressionApplyBtn\" type=\"button\">載入並播放常見進行</button>\n        <div class=\"progression-tools\"><input class=\"sb-input\" id=\"progressionSearch\" placeholder=\"搜尋進行\" aria-label=\"搜尋常見進行\"><button class=\"sb-btn\" id=\"progressionPreviewBtn\" type=\"button\">預聽</button><button class=\"sb-btn\" id=\"progressionFavoriteBtn\" type=\"button\">收藏</button></div>\n        <div class=\"progression-summary\" id=\"progressionSummary\" aria-live=\"polite\">選擇進行後顯示羅馬數字與音名摘要</div>\n        <div class=\"progression-io\"><button class=\"sb-btn\" id=\"progressionExportBtn\" type=\"button\">匯出自訂進行</button><button class=\"sb-btn\" id=\"progressionImportBtn\" type=\"button\">匯入自訂進行</button><input id=\"progressionImportInput\" type=\"file\" accept=\"application/json,.json\" hidden></div>")

s=s.replace("function renderMiniPiano(activeMidis,height){\n  if(!height)height='72px';", "function renderMiniPiano(activeMidis,height){\n  if(!height)height='72px';\n  if(S.level==='Exam')height='224px';")
s=s.replace("const examClass=(m)=>S.level==='Exam'&&S.examFeedback?.[m]?` exam-${S.examFeedback[m]}`:' ';", "const examClass=(m)=>S.level==='Exam'&&S.examFeedback?.[m]?` exam-${S.examFeedback[m]}`:'';")
# support current exact line if no space variant
s=s.replace("const examClass=(m)=>S.level==='Exam'&&S.examFeedback?.[m]?` exam-${S.examFeedback[m]}`:'';", "const examClass=(m)=>S.level==='Exam'&&S.examFeedback?.[m]?` exam-${S.examFeedback[m]}`:'';")
s=s.replace("if(S.level==='Exam'&&S.examActive)handleExamKey(midiValue,key);", "if(S.level==='Exam'&&S.examActive)handleExamKey(midiValue,key);")
# only add hint visualization when explicitly enabled
s=s.replace("const on=activeMidis.some(am=>am===m);", "const on=activeMidis.some(am=>am===m);\n        const hint=S.level==='Exam'&&S.examActive&&S.examKeyboardHint&&S.examQuestion?.midis?.includes(m)?' exam-hint':'';")
s=s.replace("${examClass(m)}'", "${examClass(m)}${hint}'")
s=s.replace("const bon=activeMidis.some(am=>am===bm);", "const bon=activeMidis.some(am=>am===bm);\n        const hint=S.level==='Exam'&&S.examActive&&S.examKeyboardHint&&S.examQuestion?.midis?.includes(bm)?' exam-hint':'';")
s=s.replace("${examClass(bm)}'", "${examClass(bm)}${hint}'")

# exam screen auto-hide settings body while active and show completion series
s=s.replace("const content=`<section class=\"exam-panel\"", "const series=S.examScoreSeries||[];\n  const chart=series.length?`<div class=\"exam-score-chart\" aria-label=\"成績曲線\">${series.map((v,i)=>`<span style=\"height:${Math.max(8,Math.min(100,v))}%\" title=\"第 ${i+1} 題 ${v}%\"></span>`).join('')}</div>`:'';\n  const content=`<section class=\"exam-panel\"")
s=s.replace("</section>\n  <section class=\"visual-area\">", "${!S.examActive&&S.examQuestionCount>=S.examQuestionLimit?`<div class=\"exam-completion\"><strong>本場完成</strong>${chart}<button class=\"sb-btn green\" id=\"examWeaknessNextBtn\" type=\"button\">依弱點開始下一場</button></div>`:''}</section>\n  <section class=\"visual-area\">")
# save setting and favorites helper before saveExamSettings
marker="function saveExamSettings(){"
helpers="""function saveProgressionFavorites(){try{localStorage.setItem('kimichord.progressionFavorites',JSON.stringify(S.progressionFavorites||[]));}catch(error){}}\nfunction progressionRoman(index){return ['I','ii','iii','IV','V','vi','vii°'][index%7]||'I';}\nfunction progressionSummary(item){if(!item)return'選擇進行後顯示羅馬數字與音名摘要';return (item.sequence||[]).map((c,i)=>`${progressionRoman(i)}（${c.note||'?'} ${c.q||''}）`).join(' → ');}\nfunction updateProgressionSummary(){const item=selectedCommonProgression();const el=document.getElementById('progressionSummary');if(el)el.textContent=progressionSummary(item);const fav=document.getElementById('progressionFavoriteBtn');if(fav&&item)fav.textContent=(S.progressionFavorites||[]).includes(item.id)?'取消收藏':'收藏';}\n"""
s=s.replace(marker,helpers+marker)
# filter catalog select on search without changing source list
s=s.replace("select.innerHTML=list.map((item,index)=>`<option value=\"${item.id}\">${item.label}</option>`).join('');", "const query=String(S.progressionSearch||'').trim().toLowerCase();const shown=query?list.filter(item=>`${item.label} ${progressionSummary(item)}`.toLowerCase().includes(query)):list;\n  select.innerHTML=shown.map((item,index)=>`<option value=\"${item.id}\">${item.label}</option>`).join('');")
s=s.replace("S.commonProgressionId=select.value;\n}", "S.commonProgressionId=select.value;updateProgressionSummary();\n}",1)
# start exam hide settings
s=s.replace("S.level='Exam';S.examActive=true;", "S.level='Exam';S.examSettingsCollapsed=true;S.examActive=true;")
# save score series on finish if not present
s=s.replace("S.examQuestionCount>=S.examQuestionLimit){", "S.examQuestionCount>=S.examQuestionLimit){\n    S.examScoreSeries=S.examScoreSeries||[];")
s=s.replace("S.examQuestionCount=0;S.examCorrectCount=0;", "S.examQuestionCount=0;S.examCorrectCount=0;S.examScoreSeries=[];")
# settings save include hint
s=s.replace("questionLimit:S.examQuestionLimit}));", "questionLimit:S.examQuestionLimit,keyboardHint:S.examKeyboardHint}));")
# CSS before closing style
css="""\n.exam-settings-toggle{margin:4px 0;width:100%;}.exam-hint-toggle{display:flex;align-items:center;gap:5px;color:var(--text3);font-size:8px;margin-top:5px}.exam-hint-toggle input{accent-color:var(--accent)}.exam-score-chart{height:64px;display:flex;align-items:flex-end;gap:3px;padding:6px;border:1px solid var(--border);border-radius:4px;background:var(--bg);margin:6px 0}.exam-score-chart span{flex:1;min-width:2px;background:var(--accent);border-radius:2px 2px 0 0}.exam-completion{margin-top:6px;padding:6px;border:1px solid var(--green);border-radius:5px;background:color-mix(in srgb,var(--green) 8%,var(--bg));font-size:9px}.progression-tools,.progression-io{display:grid;grid-template-columns:minmax(0,1fr) repeat(2,minmax(0,auto));gap:4px;margin-top:5px}.progression-io{grid-template-columns:repeat(2,minmax(0,1fr))}.progression-summary{margin-top:5px;padding:5px;border:1px solid var(--border);border-radius:4px;color:var(--text2);font-size:8px;line-height:1.35;max-height:56px;overflow:auto;word-break:break-word}.piano-mini:has(.exam-hint){min-height:224px}.p-mini-w.exam-hint,.p-mini-b.exam-hint{box-shadow:inset 0 0 0 3px #4c8df7;background:#dbeafe;color:#123}.p-mini-b.exam-hint{background:#2563eb;color:#fff}.piano-mini .piano{min-height:100%}@media(max-width:700px){.progression-tools,.progression-io{grid-template-columns:1fr 1fr}.progression-tools .sb-input{grid-column:1/-1}.exam-completion{font-size:8px}.piano-mini{max-width:100%;overflow:hidden}}\n"""
s=s.replace('</style>',css+'</style>',1)
# event bindings additions before existing common length binding
needle="document.getElementById('commonProgressionLengthSelect').onchange=function()"
handlers="""const examHint=document.getElementById('examKeyboardHint');if(examHint){examHint.checked=Boolean(S.examKeyboardHint);examHint.onchange=function(){S.examKeyboardHint=this.checked;saveExamSettings();if(S.level==='Exam')renderExam();};}\nconst examToggle=document.getElementById('examSettingsToggle');if(examToggle)examToggle.onclick=function(){S.examSettingsCollapsed=!S.examSettingsCollapsed;const body=document.getElementById('examSettingsBody');if(body)body.hidden=S.examSettingsCollapsed;this.setAttribute('aria-expanded',String(!S.examSettingsCollapsed));};\nconst progressionSearch=document.getElementById('progressionSearch');if(progressionSearch)progressionSearch.oninput=function(){S.progressionSearch=this.value;populateCommonProgressions();};\nconst progressionPreview=document.getElementById('progressionPreviewBtn');if(progressionPreview)progressionPreview.onclick=function(){playSelectedCommonProgression();};\nconst progressionFavorite=document.getElementById('progressionFavoriteBtn');if(progressionFavorite)progressionFavorite.onclick=function(){const item=selectedCommonProgression();if(!item)return;const set=new Set(S.progressionFavorites||[]);if(set.has(item.id))set.delete(item.id);else set.add(item.id);S.progressionFavorites=[...set];saveProgressionFavorites();updateProgressionSummary();};\nconst progressionExport=document.getElementById('progressionExportBtn');if(progressionExport)progressionExport.onclick=function(){const item=selectedCommonProgression();const payload={version:1,label:item?.label||'自訂進行',sequence:item?.sequence||S.progression||[]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kimichord-progression.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);};\nconst progressionImport=document.getElementById('progressionImportBtn'),progressionFile=document.getElementById('progressionImportInput');if(progressionImport&&progressionFile){progressionImport.onclick=function(){progressionFile.click();};progressionFile.onchange=function(){const file=this.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result);if(!Array.isArray(payload.sequence)||!payload.sequence.length)throw new Error('empty');S.progression=payload.sequence;renderProgression();render();showToast('已匯入自訂進行');}catch(error){showToast('匯入格式無效');}};reader.readAsText(file);};}\n"""
s=s.replace(needle,handlers+needle)
# add onchange summary after select handler
s=s.replace("document.getElementById('commonProgressionSelect').onchange=function(){S.commonProgressionId=this.value;};", "document.getElementById('commonProgressionSelect').onchange=function(){S.commonProgressionId=this.value;updateProgressionSummary();};")
# keyboard hint setting initial collapsed state in render
s=s.replace("if(examControls)examControls.hidden=S.level!=='Exam';", "if(examControls)examControls.hidden=S.level!=='Exam';\n  const examBody=document.getElementById('examSettingsBody');if(examBody)examBody.hidden=S.examSettingsCollapsed&&S.examActive;")
# weak next button listener in renderExam after area innerHTML
s=s.replace("if(area)area.innerHTML=content;\n  updateExamStats();", "if(area)area.innerHTML=content;\n  const weakNext=document.getElementById('examWeaknessNextBtn');if(weakNext)weakNext.onclick=function(){S.examSettingsCollapsed=false;S.examKeys=[];S.examChordTypes=[];startExam();};\n  updateExamStats();")
p.write_text(s)
